### ISSUE TITLE
Moving mouse in 1px when you set step, doesn't work correct 

### ISSUE THREAD

**Issue by Dmitry-Sokolov** [swiftcarrot/react-input-slider#42]
When setting step 1, min value to 10 and max to 15, then try to drag the mouse, then the value is jumping in +/- 2px, even if mouse moves on +2px, then the value can jump on -2 there is no stop on point.
When trying set text size/line height with a slider it like convulsions.

**Comment by wangzuo** [comment]
can you post a example with https://codesandbox.io ?
