### ISSUE TITLE
impossible to disable the slider

### ISSUE THREAD

**Issue by LRNida** [swiftcarrot/react-input-slider#45]
Like most input elements, sliders occasionally need to be disabled.
Right now there doesn't seem to be a way to do this. Adding a boolean prop (& required functionality) would be a very useful addition. Both in general and for a project I'm now working on.

**Comment by wangzuo** [comment]
Good point, working on it.

**Comment by wangzuo** [comment]
available in `5.1.0` with `<Slider disabled />`
