### ISSUE TITLE
onDragEnd and onDragStart never gives the good value

### ISSUE THREAD

**Issue by IamFonky** [swiftcarrot/react-input-slider#53]
Is this example, the dragStart and dragEnd events give me completely out of bound values.
Am I doing something wrong?

https://codesandbox.io/s/funny-pine-jfphn

**Comment by wangzuo** [comment]
dragStart & dragEnd only pass event object now https://github.com/swiftcarrot/react-input-slider/blob/master/src/slider.js#L100
