### ISSUE TITLE
For y axis fill color direction is wrong

### ISSUE THREAD

**Issue by debotos** [swiftcarrot/react-input-slider#54]
For the y-axis, fill color is starting from top to bottom.
But to use it as a volume controller it should be bottom to top.
Any props or attribute to change this behavior?

**Comment by debotos** [comment]
Currently, I am doing in this way, Kind of a reverse thing,
```js
<Slider
  axis="y"
  ystep={0.01}
  ymin={0}
  ymax={1}
  y={1 - this.state.volume}
  onChange={({ y }) => this.setState({ volume: parseFloat(1-y) })}
  styles={{
    track: {
      backgroundColor: "#5e72e4",
      height: "100px",
    },
    active: {
      backgroundColor: "#ddd",
    },
  }}
/>;

```

**Comment by wangzuo** [comment]
Just added reverse support in `5.1.5` https://github.com/swiftcarrot/react-input-slider#props
