### ISSUE TITLE
Add support for the hover style option

### ISSUE THREAD

**Issue by RodolfoSilva** [swiftcarrot/react-input-slider#55]
I need set a custom behavior when the user pass the mouse hover or focus in the thumb change the style, but custom style don't support this functionality.

Example:

https://codesandbox.io/s/objective-sound-o4s5x

**Comment by wangzuo** [comment]
Updated the styling for handler and thumb https://github.com/swiftcarrot/react-input-slider/pull/57

**Comment by wangzuo** [comment]
released in `5.1.6`
