### ISSUE TITLE
Update for React 17

### ISSUE THREAD

**Issue by Enchiridion** [swiftcarrot/react-input-slider#78]
Hi, Could you update this to support React 17?

**Comment by Snazzyham** [comment]
@Enchiridion it actually still works on React 17, I just used it. If you're having an issue installing, try passing the `--legacy-peer-deps` flag to `npm`. 

Hope this helps!

**Comment by wangzuo** [comment]
its due to the peer deps?

**Comment by wangzuo** [comment]
Just published the update in `6.0.1`, please reopen if still not working.
